export type CatalogProduct = {
  id: number;
  nombre: string;
  precio: number;
  stock: number;
  estado: boolean;
  destacado: boolean;
  oferta: boolean;
  imagenUrl: string | null;
  categoriaId: number;
  descripcion?: string;
  categoria?: { id: number; nombre: string };
};

export const catalogCategories = [
  { id: 1, nombre: 'Llaveros' },
  { id: 2, nombre: 'Mates y Bombillas' },
  { id: 3, nombre: 'Porta Sahumerios' },
  { id: 4, nombre: 'Dijes y Accesorios' },
  { id: 5, nombre: 'Soportes y Organizadores' },
  { id: 6, nombre: 'Juguetes y Juegos' },
  { id: 7, nombre: 'Personajes y Figuras' },
  { id: 8, nombre: 'Utilidades del Hogar' },
];

export const catalogProducts: CatalogProduct[] = [
  {
    id: 1,
    nombre: 'Llavero Personalizado con Nombre',
    precio: 2500,
    stock: 50,
    estado: true,
    destacado: true,
    oferta: false,
    imagenUrl: '/categorias/llaveros.png',
    categoriaId: 1,
    descripcion: 'Llavero impreso en 3D con el nombre o texto que quieras. Elegí color y tipografía.',
    categoria: { id: 1, nombre: 'Llaveros' },
  },
  {
    id: 2,
    nombre: 'Llavero Búho Articulado',
    precio: 3000,
    stock: 35,
    estado: true,
    destacado: false,
    oferta: true,
    imagenUrl: '/categorias/llaveros.png',
    categoriaId: 1,
    descripcion: 'Llavero flexi de búho con alas articuladas. Un clásico que siempre gusta.',
    categoria: { id: 1, nombre: 'Llaveros' },
  },
  {
    id: 3,
    nombre: 'Mate Imperial con Virola Personalizada',
    precio: 12000,
    stock: 20,
    estado: true,
    destacado: true,
    oferta: false,
    imagenUrl: '/categorias/mate-arg.jpg',
    categoriaId: 2,
    descripcion: 'Mate impreso en 3D apto para yerba, con virola personalizada a tu gusto.',
    categoria: { id: 2, nombre: 'Mates y Bombillas' },
  },
  {
    id: 4,
    nombre: 'Porta Sahumerio Luna y Estrellas',
    precio: 3500,
    stock: 30,
    estado: true,
    destacado: true,
    oferta: false,
    imagenUrl: '/categorias/sahumerios.png',
    categoriaId: 3,
    descripcion: 'Base porta sahumerios y conos con diseño lunar. Varios colores disponibles.',
    categoria: { id: 3, nombre: 'Porta Sahumerios' },
  },
  {
    id: 5,
    nombre: 'Dije Dragón Articulado',
    precio: 2800,
    stock: 25,
    estado: true,
    destacado: false,
    oferta: true,
    imagenUrl: '/categorias/dijes.png',
    categoriaId: 4,
    descripcion: 'Dije flexi articulado impreso en una sola pieza. Ideal para collar o llavero.',
    categoria: { id: 4, nombre: 'Dijes y Accesorios' },
  },
  {
    id: 6,
    nombre: 'Rompecabezas 3D T-Rex',
    precio: 8500,
    stock: 15,
    estado: true,
    destacado: false,
    oferta: false,
    imagenUrl: '/categorias/juguetes.png',
    categoriaId: 6,
    descripcion: 'Puzzle 3D de T-Rex armable sin pegamento. Diversión garantizada.',
    categoria: { id: 6, nombre: 'Juguetes y Juegos' },
  },
  {
    id: 7,
    nombre: 'Figura Articulada Panda Flexi',
    precio: 4500,
    stock: 22,
    estado: true,
    destacado: true,
    oferta: false,
    imagenUrl: '/categorias/personajes.png',
    categoriaId: 7,
    descripcion: 'Personaje flexible articulado impreso en una sola pieza. Se mueve y se dobla.',
    categoria: { id: 7, nombre: 'Personajes y Figuras' },
  },
  {
    id: 8,
    nombre: 'Organizador de Escritorio Modular',
    precio: 9500,
    stock: 18,
    estado: true,
    destacado: false,
    oferta: false,
    imagenUrl: '/categorias/utilidades.png',
    categoriaId: 8,
    descripcion: 'Organizador modular para escritorio: apilable y ampliable según tu necesidad.',
    categoria: { id: 8, nombre: 'Utilidades del Hogar' },
  },
  {
    id: 9,
    nombre: 'Combo Regalo 3D: Llavero + Dije + Porta Sahumerio',
    precio: 7500,
    stock: 10,
    estado: true,
    destacado: true,
    oferta: true,
    imagenUrl: '/portada.jpg',
    categoriaId: 1,
    descripcion: 'Combo ideal para regalar: elegí los modelos y colores de cada pieza.',
    categoria: { id: 1, nombre: 'Llaveros' },
  },
  {
    id: 10,
    nombre: 'Mate Temático Iron Man',
    precio: 5500,
    stock: 12,
    estado: true,
    destacado: true,
    oferta: false,
    imagenUrl: '/categorias/mate-iroman.jpg',
    categoriaId: 2,
    descripcion: 'Mate 3D inspirado en Iron Man. Apto para yerba, diseño exclusivo NH3D.',
    categoria: { id: 2, nombre: 'Mates y Bombillas' },
  },
  {
    id: 11,
    nombre: 'Mate Temático Batman',
    precio: 5500,
    stock: 14,
    estado: true,
    destacado: false,
    oferta: false,
    imagenUrl: '/categorias/mate-batman.jpg',
    categoriaId: 2,
    descripcion: 'Mate 3D con diseño de Batman. Pieza de colección para todos los días.',
    categoria: { id: 2, nombre: 'Mates y Bombillas' },
  },
  {
    id: 12,
    nombre: 'Mate Calavera 3D',
    precio: 5000,
    stock: 16,
    estado: true,
    destacado: true,
    oferta: false,
    imagenUrl: '/categorias/calavera-mate.jpg',
    categoriaId: 2,
    descripcion: 'Mate con diseño de calavera impreso en 3D. Estilo único y llamativo.',
    categoria: { id: 2, nombre: 'Mates y Bombillas' },
  },
  {
    id: 13,
    nombre: 'Mate Cactus',
    precio: 4800,
    stock: 18,
    estado: true,
    destacado: false,
    oferta: true,
    imagenUrl: '/categorias/mate-captus.jfif',
    categoriaId: 2,
    descripcion: 'Mate 3D con forma de cactus. Divertido, práctico y apto para yerba.',
    categoria: { id: 2, nombre: 'Mates y Bombillas' },
  },
  {
    id: 14,
    nombre: 'Soporte Notebook Modelo Benja',
    precio: 14000,
    stock: 10,
    estado: true,
    destacado: true,
    oferta: false,
    imagenUrl: '/categorias/soporte-note-benja.png',
    categoriaId: 5,
    descripcion: 'Soporte elevador para notebook impreso en 3D. Mejora tu postura al trabajar.',
    categoria: { id: 5, nombre: 'Soportes y Organizadores' },
  },
  {
    id: 15,
    nombre: 'Soporte Notebook Modelo Jere',
    precio: 13500,
    stock: 8,
    estado: true,
    destacado: false,
    oferta: false,
    imagenUrl: '/categorias/soporte-note-jere.jpg',
    categoriaId: 5,
    descripcion: 'Base soporte para notebook con inclinación ergonómica. Liviano y resistente.',
    categoria: { id: 5, nombre: 'Soportes y Organizadores' },
  },
  {
    id: 16,
    nombre: 'Soporte Notebook Modelo Mody',
    precio: 15000,
    stock: 6,
    estado: true,
    destacado: false,
    oferta: false,
    imagenUrl: '/categorias/soporte-note-mody.jpg',
    categoriaId: 5,
    descripcion: 'Soporte plegable para notebook. Ideal para escritorios compactos.',
    categoria: { id: 5, nombre: 'Soportes y Organizadores' },
  },
  {
    id: 17,
    nombre: 'Soporte Notebook Modelo Nacho',
    precio: 13000,
    stock: 9,
    estado: true,
    destacado: false,
    oferta: true,
    imagenUrl: '/categorias/soporte-note-nacho.jpg',
    categoriaId: 5,
    descripcion: 'Soporte minimalista para notebook. Varios colores a elección.',
    categoria: { id: 5, nombre: 'Soportes y Organizadores' },
  },
];

export function getCatalogProductById(id: number) {
  return catalogProducts.find((product) => product.id === id) ?? null;
}
